spring:
  application: 
    name: EurekaServer
  profiles: server1
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://server2:8762/eureka 
---
spring: 
  application: 
    name: EurekaServer
  profiles: server2
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka 
  
  